export const artificer = {
    name: "Artificer",
    source: "UAArtificer",
    page: 1,
    isReprinted: true,
    hd: {
        number: 1,
        faces: 8,
    },
    proficiency: ["con", "int"],
    spellcastingAbility: "int",
    casterProgression: "1/2",
    cantripProgression: [
        2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4,
    ],
    spellsKnownProgression: [
        0, 0, 3, 4, 4, 4, 5, 6, 6, 7, 8, 8, 9, 10, 10, 11, 11, 11, 12, 13,
    ],
    startingProficiencies: {
        armor: ["light", "medium"],
        weapons: ["simple"],
        tools: [
            "{@item Thieves' tools|PHB}",
            "{@item tinker's tools|PHB}",
            "one type of {@item artisan's tools|PHB} of your choice",
        ],
        skills: [
            {
                choose: {
                    from: [
                        "arcana",
                        "deception",
                        "history",
                        "investigation",
                        "medicine",
                        "nature",
                        "religion",
                        "sleight of hand",
                    ],
                    count: 2,
                },
            },
        ],
    },
    startingEquipment: {
        additionalFromBackground: true,
        default: [
            "(a) a {@item handaxe|phb} and a {@item light hammer|phb} or (b) any two {@filter simple weapons|items|source=phb|category=basic|type=simple weapon}",
            "a {@item light crossbow|phb} and {@item crossbow bolts (20)|phb|20 bolts}",
            "(a) {@item scale mail|phb} or (b) {@item studded leather armor|phb}",
            "{@item thieves' tools|phb} and a {@item dungeoneer's pack|phb}",
        ],
        defaultData: [
            {
                a: ["handaxe|phb", "light hammer|phb"],
                b: [
                    {
                        equipmentType: "weaponSimple",
                        quantity: 2,
                    },
                ],
            },
            {
                _: ["light crossbow|phb", "crossbow bolts (20)|phb"],
            },
            {
                a: ["scale mail|phb"],
                b: ["studded leather armor|phb"],
            },
            {
                _: ["thieves' tools|phb", "dungeoneer's pack|phb"],
            },
        ],
    },
    classTableGroups: [
        {
            colLabels: ["{@filter Spells Known|spells|class=artificer (uaa)}"],
            rows: [
                [0],
                [0],
                [3],
                [4],
                [4],
                [4],
                [5],
                [6],
                [6],
                [7],
                [8],
                [8],
                [9],
                [10],
                [10],
                [11],
                [11],
                [11],
                [12],
                [13],
            ],
        },
        {
            title: "Spell Slots per Spell Level",
            colLabels: [
                "{@filter 1st|spells|level=1|class=Artificer (UAA)}",
                "{@filter 2nd|spells|level=2|class=Artificer (UAA)}",
                "{@filter 3rd|spells|level=3|class=Artificer (UAA)}",
                "{@filter 4th|spells|level=4|class=Artificer (UAA)}",
            ],
            rowsSpellProgression: [
                [0, 0, 0, 0],
                [0, 0, 0, 0],
                [2, 0, 0, 0],
                [3, 0, 0, 0],
                [3, 0, 0, 0],
                [3, 0, 0, 0],
                [4, 2, 0, 0],
                [4, 2, 0, 0],
                [4, 2, 0, 0],
                [4, 3, 0, 0],
                [4, 3, 0, 0],
                [4, 3, 0, 0],
                [4, 3, 2, 0],
                [4, 3, 2, 0],
                [4, 3, 2, 0],
                [4, 3, 3, 0],
                [4, 3, 3, 0],
                [4, 3, 3, 0],
                [4, 3, 3, 1],
                [4, 3, 3, 1],
            ],
        },
    ],
    classFeatures: [
        {
            classFeature: "Artificer Specialist|Artificer|UAArtificer|1",
            gainSubclassFeature: true,
        },
        "Magic Item Analysis|Artificer|UAArtificer|1",
        "Tool Expertise|Artificer|UAArtificer|2",
        "Wondrous Invention|Artificer|UAArtificer|2",
        {
            classFeature: "Masterwork Feature|Artificer|UAArtificer|3",
            gainSubclassFeature: true,
        },
        "Spellcasting|Artificer|UAArtificer|3",
        "Infuse Magic|Artificer|UAArtificer|4",
        "Ability Score Improvement|Artificer|UAArtificer|4",
        "Proficiency Versatility|Artificer|UAArtificer|4|UAClassFeatureVariants",
        "Superior Attunement|Artificer|UAArtificer|5",
        "Wondrous Invention|Artificer|UAArtificer|5",
        "Mechanical Servant|Artificer|UAArtificer|6",
        "Ability Score Improvement|Artificer|UAArtificer|8",
        "Proficiency Versatility|Artificer|UAArtificer|8|UAClassFeatureVariants",
        {
            classFeature: "Masterwork Feature|Artificer|UAArtificer|9",
            gainSubclassFeature: true,
        },
        "Wondrous Invention|Artificer|UAArtificer|10",
        "Ability Score Improvement|Artificer|UAArtificer|12",
        "Proficiency Versatility|Artificer|UAArtificer|12|UAClassFeatureVariants",
        {
            classFeature: "Masterwork Feature|Artificer|UAArtificer|14",
            gainSubclassFeature: true,
        },
        "Superior Attunement|Artificer|UAArtificer|15",
        "Wondrous Invention|Artificer|UAArtificer|15",
        "Ability Score Improvement|Artificer|UAArtificer|16",
        "Proficiency Versatility|Artificer|UAArtificer|16|UAClassFeatureVariants",
        {
            classFeature: "Masterwork Feature|Artificer|UAArtificer|17",
            gainSubclassFeature: true,
        },
        "Ability Score Improvement|Artificer|UAArtificer|18",
        "Proficiency Versatility|Artificer|UAArtificer|18|UAClassFeatureVariants",
        "Soul of Artifice|Artificer|UAArtificer|20",
    ],
    subclassTitle: "Artificer Specialist",
};
